uploads = []
outputs = []

[[generated]]
id = "-nG7QqxH3B_L0PUlQliPp"
uri = "file://artifacts/my-wife/public/her/wedding-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_lGcpP_S-xVNikz0R06Ub"
uri = "file://artifacts/my-wife/public/her/wedding-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "k8pCdvjtF8A6oDs334A1K"
uri = "file://artifacts/my-wife/public/her/wedding-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "L5cnz7DL5IfC1tKPAE83c"
uri = "file://artifacts/my-wife/public/her/wedding-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GX_NmpnYwwOK6SAAkSA-m"
uri = "file://artifacts/my-wife/public/her/church-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "eiHpLFaus9K3uC5qc8hp5"
uri = "file://artifacts/my-wife/public/her/church-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Umh8SyymwGGCPR29fctRB"
uri = "file://artifacts/my-wife/public/her/church-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1UCNoJIqoyXaM8_hIHGp6"
uri = "file://artifacts/my-wife/public/her/party-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Rdrl_B5Szlda3TtLYL595"
uri = "file://artifacts/my-wife/public/her/party-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wtCFoqqahdG3MXVqpzPu7"
uri = "file://artifacts/my-wife/public/her/party-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XSpChJf0q5b_U0jKwR6tQ"
uri = "file://artifacts/my-wife/public/her/selfie-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DTtEdhLFZCqnBkN2OYeyS"
uri = "file://artifacts/my-wife/public/her/hot-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4HMSD6R8ccgG8wwQ-pC3h"
uri = "file://artifacts/my-wife/public/her/hot-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "15Is4u9TSz-ynr470KPSn"
uri = "file://artifacts/my-wife/public/her/outdoor-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FAsdom6vCUQ518jk1DsXc"
uri = "file://artifacts/my-wife/public/her/outdoor-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "N3XPqfseHs-zFvJpHDIqP"
uri = "file://artifacts/my-wife/public/her/school-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IDSi-UAnuiexDyYbGxCZa"
uri = "file://artifacts/my-wife/public/her/party-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "CTecGQp4gUB1aLhdAuIiK"
uri = "file://artifacts/my-wife/public/her/daily-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mZ1E3D-S7NsE9p1cwBJwo"
uri = "file://artifacts/my-wife/public/her/club-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WOBDXAYB86kaOcG8ocPhx"
uri = "file://artifacts/my-wife/public/her/outdoor-3.png"
type = "image"
title = "generated_image"
